In [6]:
import dash
from dash import html, dcc, dash_table, Input, Output
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
from shiny.express import render, input, ui
from shinywidgets import reder_plotly

ModuleNotFoundError: No module named 'shiny'

In [2]:
df = pd.read_excel("E:/Term2/WERI/thesis_AB/proposal/initial/04/dataset_acc.xlsx", sheet_name="Sheet1")
df

,Renewable,Type of Source,Year,اشتراک,امور,اشتراک برق,Basin,Name of Source,Shahrestan,Section,...,کنتور هوشمند,POLY_ID,sad,حجم مخزن در تراز نرمال,حجم آب قابل تنظیم سالیانه,ورودی سال آبی 1402-03,حجم آب ذخیزه شده حال حاضر(1403),حجم آب ذخیزه شده سال قبل(1402),درصد پر بودن مخزن1403,درصد پر بودن مخزن 1402
0,تجدید پذیر,زیرزمینی,1402-03,518187.0,آب مشهد,0.0,مشهد - چناران,2,مشهد,4,...,ندارد,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,تجدید پذیر,زیرزمینی,1402-03,518189.0,آب مشهد,0.0,مشهد - چناران,0,مشهد,4,...,ندارد,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,تجدید پذیر,زیرزمینی,1402-03,518190.0,آب مشهد,451850.0,مشهد - چناران,1,مشهد,4,...,ندارد,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,تجدید پذیر,زیرزمینی,1402-03,518217.0,آب مشهد,0.0,مشهد - چناران,0,مشهد,4,...,ندارد,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,تجدید پذیر,زیرزمینی,1402-03,518246.0,آب مشهد,0.0,مشهد - چناران,2,مشهد,4,...,ندارد,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5968,تجدید پذیر,سطحی,1402-03,NaN,NaN,NaN,مشهد - چناران,سد يام,نيشابور,4,...,NaN,NaN,سد يام,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5969,تجدید پذیر,سطحی,1402-03,NaN,NaN,NaN,مشهد - چناران,سد دولت آباد,چناران,3,...,NaN,1.0,سد دولت آباد,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5970,تجدید پذیر,سطحی,1402-03,NaN,NaN,NaN,مشهد - چناران,سد قره تیکان,مشهد,4,...,NaN,NaN,سد قره تیکان,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5971,تجدید پذیر,سطحی,1402-03,NaN,NaN,NaN,مشهد - چناران,سد چهچهه,مشهد,4,...,NaN,NaN,سد چهچهه,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5972,تجدید پذیر,سطحی,1402-03,NaN,NaN,NaN,مشهد - چناران,سد بار,نيشابور,4,...,NaN,NaN,سد بار,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
ui.page_opts(title="Water Dashboard", fillabble=True)

ui.input_numeric("n", "Number of Items", 5, min=0, max=20)

@reactive.calc
def dat():
    infile = pd.read_excel("E:/Term2/WERI/thesis_AB/proposal/initial/04/dataset_acc.xlsx", sheet_name="Sheet1")
    return infile

@render_plotly
def plot1():
    df = dat()
    top_value = df.groupby('Renewable')["Value"].sum().nlargest(input.n()).reset_index()
    return px.bar(top_value, x = "Renewable", y='quantity_ordered')


@render_plotly
def volume_over_time():
    df = dat()
    print(df)
                




    

# Initialize the Dash app with a better styling theme
app = dash.Dash()

app.layout = html.Div

NameError: name 'ui' is not defined